- hosts: esxi
  tasks:
    - name: copy base
      copy: 
        src: /inventory/script/esxi/base
        dest: /root/
        mode: u=rx,g=r,o=r
        force: yes
      tags: copy, copy base
    - name: copy crontab
      copy: 
        src: /inventory/script/esxi/etc/crontab
        dest: /var/spool/cron/crontabs/root
        mode: u=r,g=r,o=r+t
        force: yes
      tags: copy, copy-crontab
    - name: copy cron restart
      copy: 
        src: /inventory/script/esxi/restart_cron
        dest: /root
        mode: u=rx,g=r,o=r
        force: yes
      tags: copy, copy-cron-restart, cron-restart
    - name: crontab restart
      command: sh /root/restart_cron
      args:
        removes: /root/restart_cron
      register: result
      tags: cron-restart
    - name: print crontab restart
      debug: var=result.stdout_lines
      tags: cron-restart
    - name: get all vms name
      command: sh /root/base all
      register: content
      args:
        removes: /root/base 
      tags: all-vms, all-vm-name
    - name: print all vms name
      debug: var=content.stdout_lines 
      tags: all-vms, all-vm-name
    - name: get vm id
      command: sh /root/base id "{{name}}" # ansible-playbook esxi.yml -e 'name="DSM"' --tags id
      register: id
      args: 
        removes: /root/base
      tags: id
    - name: print id
      debug: var=id.stdout_lines 
      tags: id
    


