- hosts: esxi
  tasks:
    - name: copy base
      copy: 
        src: /inventory/script/esxi/base
        dest: /root/
        mode: u=rx,g=r,o=r
        force: yes
      tags: copy
    - name: get all vms name
      command: sh /root/base all
      register: content
      args:
        removes: /root/base 
      tags: all-vms, all-vm-name
    - name: print all vms name
      debug: var=content.stdout_lines 
      tags: all-vms, all-vm-name
    - name: get venom state
      command: sh /root/base state venom
      register: state
      args:
        removes: /root/base 
      tags: venom-state
    - name: print venom state
      debug: var=state.stdout_lines
      tags: venom-state
    - name: start venom
      command: sh /root/base start venom
      register: output
      tags: start-venom
    - name: print start venom
      debug: var=output.stdout_lines
      tags: start-venom 
    - name: get windows server 2019 state
      command: sh /root/base state WindowsServer2019
      register: state
      tags: win2019-state
    - name: pring windows server 2019 state
      debug: var=state.stdout_lines
      tags: win2019-state 


