- hosts: nero
  roles:
      - openwrt
  tasks:
    - import_tasks: ./nero/service.yml
    - import_tasks: ./nero/config.yml
    - name: run magneto
      service: 
        name: magneto
        state: restarted
        enabled: yes
      tags: magneto
    - name: run wolverine
      service: 
        name: wolverine
        state: restarted
        enabled: yes
      tags: wolverine
    - name: run cyclops
      service: 
        name: cyclops
        state: restarted
        enabled: yes
      tags: cyclops
        