- hosts: barbarossia
  roles:
      - openwrt
  tasks:
    - import_tasks: ./router/service.yml
    - import_tasks: ./router/config.yml
    - name: add ip to gfwlist
      command: sh /root/iptab add 192.168.1.12 1180
      args:
        removes: /root/iptab
      tags: add-gfwlist
    - name: remove ip to gfwlist
      command: sh /root/iptab remove 192.168.1.12 1180
      args:
        removes: /root/iptab
      tags: remove-gfwlist
    - name: update ip to gfwlist # ansible-playbook router.yml -e 'ip="192.168.1.11" old_port="1480" new_port="1280"' --tags update-gfwlist
      command: sh /root/iptab update 192.168.1.12 1180 1280
      args:
        removes: /root/iptab
      tags: update-gfwlist
    - name: check ip exist on gfwlist
      command: sh /root/iptab exist 192.168.1.12
      args:
        removes: /root/iptab
      register: output
      tags: check-gfwlist
    - name: print ip exist on gfwlist
      debug: var=output.stdout_lines
      tags: check-gfwlist