- hosts: home
  tasks:
    - name: copy sync-download
      copy: 
        src: /inventory/script/home/sync-download
        dest: /root/sync-download
        mode: u=rx,g=r,o=r
        force: yes
    - name: Check that the sync exists
      stat:
        path: /root/sync-download
      register: stat_result
    - name: check sync-download is exist
      command: echo "sync-download is exist"
      when: stat_result.stat.exists == True 
      register: check_result
    - debug: var=check_result.stdout

