- hosts: venom
  tasks:
    - import_tasks: ./venom/service.yml
    - name: run convert batch
      command: /usr/bin/screen -d -m /home/barbarossia/batch convert {{folder}}
      args:
        removes: /home/barbarossia/batch
      tags: convert

