---
# tasks file for trojan-gfw
#- include_tasks: service.yml

- name: Stop service
  when: op == 'update'
  command: sudo systemctl stop {{SVC}}
  become: yes

#install copy and unpacking binary
- name: Unarchive a file that needs to be downloaded (added in 2.0)
  when: op == 'install' or op == 'update'
  become: yes
  unarchive:
    src: https://github.com/trojan-gfw/trojan/releases/download/v{{remote}}/trojan-{{remote}}-linux-amd64.tar.xz
    dest: /usr/bin
    mode: '0755'
    remote_src: yes

- name: Start service
  when: op == 'update'
  command: sudo systemctl start {{SVC}}
  become: yes

- name: create server.json
  when: op == 'install'
  become: yes
  file:
    path: /etc/trojan
    state: directory
    mode: '0755'

- name: copy server.json
  when: op == 'install' 
  become: true
  template: 
    src: ./templates/server.json.j2
    dest: /etc/trojan/server.json
    mode: u=r,g=r,o=r
    force: true

- name: copy nginx.conf
  when: op == 'install' 
  become: true
  template: 
    src: ./templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: u=r,g=r,o=r
    force: true

- name: copy the systemd 
  when: op == 'install' 
  become: true
  template: 
    src: ./templates/{{SVC}}.j2
    dest: /lib/systemd/system/{{SVC}}
    mode: u=r,g=r,o=r
    force: true
  notify:
    - Reload systemd daemon
    - Enable service autostart
    - Start service
    - restart nginx

- name: show the port and psk 
  when: op == 'install' 
  shell: cat /etc/trojan/server.json
  register: content

- name: print the port and psk
  when: op == 'install' 
  debug: var=content