- name: copy Block
  copy: 
    src: /inventory/script/router/start_shaping
    dest: /root/
    mode: u=rx,g=r,o=r
    force: yes
  tags: copy, copy-block
- name: copy unBlock
  copy: 
    src: /inventory/script/router/stop_shaping
    dest: /root/
    mode: u=rx,g=r,o=r
    force: yes
  tags: copy, copy-unblock
- name: copy iptab
  copy:
    src: /inventory/script/router/iptab
    dest: /root/
    mode: u=rx,g=r,o=r
    force: yes
  tags: copy, copy-iptab
- name: copy redsocks2 conf
  copy:
    src: /inventory/script/router/etc/redsocks2.conf
    dest: /etc/redssocks2.conf
    mode: u=rw,g=r,o=r
    force: yes
  tags: copy, copy-redsocks-conf
- name: copy redsocks2 init.d 
  copy: 
    src: /inventory/script/router/etc/init.d/redsocks2
    dest: /etc/init.d/
    mode: u=rwx,g=rx,o=rx
    force: yes
  tags: copy, copy-redsocks-service