#!/bin/sh

/usr/sbin/tc qdisc del dev br-lan root

/usr/sbin/tc qdisc del dev pppoe-wan root
/usr/sbin/iptables -t mangle -D FORWARD -s 192.168.1.114 -j MARK --set-mark 20
/usr/sbin/iptables -t mangle -D FORWARD -s 192.168.1.13 -j MARK --set-mark 20