- name: copy cylops config
  copy:
    src: /inventory/script/nero/etc/v2ray/npsboost/tls.json
    dest: /etc/v2ray/npsboost/tls.json
    mode: u=rx,g=r,o=r
    force: yes
  tags: copy, copy-config, copy-cyclops-config

- name: copy magneto init.d 
  copy: 
    src: /inventory/script/nero/etc/init.d/magneto
    dest: /etc/init.d/
    mode: u=rwx,g=rx,o=rx
    force: yes
  tags: copy, copy-magneto

- name: copy wolverine init.d 
  copy: 
    src: /inventory/script/nero/etc/init.d/wolverine
    dest: /etc/init.d/
    mode: u=rwx,g=rx,o=rx
    force: yes
  tags: copy, copy-wolverine

- name: copy cyclops init.d
  copy:
    src: /inventory/script/nero/etc/init.d/cyclops
    dest: /etc/init.d/
    mode: u=rxw,g=rx,o=rx
    force: yes
  tags: copy, copy-cyclops

- name: copy connection test
  copy:
    src: /inventory/script/nero/conn-test
    dest: /root
    mode: u=rxw,g=rx,o=rx
    force: yes
  tags: copy, copy-conn-test
  
- name: copy npsboost test
  copy:
    src: /inventory/script/nero/npsboost
    dest: /root
    mode: u=rxw,g=rx,o=rx
    force: yes
  tags: copy, copy-npsboost-test