- name: Install  iperf3
  opkg: 
    name: iperf3
    state: present
  tags: install-iperf3

- name: Install  bc
  opkg: 
    name: bc
    state: present
  tags: install-bc

- name: run magneto
  service: 
    name: magneto
    state: restarted
    enabled: yes
  tags: run, magneto

- name: run wolverine
  service: 
    name: wolverine
    state: restarted
    enabled: yes
  tags: run, wolverine

- name: run cyclops
  service: 
    name: cyclops
    state: restarted
    enabled: yes
  tags: run, cyclops

- name: run connection test
  block:
    - command: sh conn-test output test {{port}}
      register: output
      args:
        chdir: /root
        removes: /root/conn-test
    - debug: 
        msg: "{{ output.stdout_lines }}"
  tags: test-conn

- name: run npsboost test
  block:
    - name: npsboost test
      command: sh /root/npsboost hk.*543
      register: output
      args:
        removes: /root/npsboost
    - debug: var=output.stdout_lines
  tags: npsboost

- name: reload cyclops
  block:
    - name: replace config
      lineinfile:
        path: /etc/v2ray/npsboost/tls.json
        regexp: '"address":'
        line: '"address": "hk-18.mitsuha-node.com",'
    - name: reload service
      service: 
        name: cyclops
        state: reloaded
        enabled: yes
  tags: reload-cyclops