#!/bin/sh /etc/rc.common
#
# Copyright (C) 2017 Ian Li <OpenSource@ianli.xyz>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=90

USE_PROCD=1
LimitNOFILE=1048576
LimitNPROC=512

start_service() {
        mkdir /var/log/redsocks2 > /dev/null 2>&1
        ulimit -n 99999
        procd_open_instance
        procd_set_param respawn
        procd_set_param command /usr/bin/redsocks2 -c /etc/redsocks2.conf
        procd_set_param file /etc/redsocks2.conf
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param pidfile /var/run/redsocks2.pid
        procd_close_instance
}